name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lint-extension:
    name: "Check extension"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: "web-ext lint"
        uses: kewisch/action-web-ext@v1
        with:
          cmd: lint
          source: src
          channel: unlisted

  tagged-release:
    name: "Tagged release"
    if: ${{ github.repository == 'Its-Alex/firefox-extension-searxng' && contains(github.ref, 'refs/tags/') }}
    runs-on: "ubuntu-latest"
    needs: [lint-extension]
    steps:
      - uses: "softprops/action-gh-release@v2"
        with:
          repository: Its-Alex/firefox-extension-searxng
          token: "${{ secrets.GITHUB_TOKEN }}"
          generate_release_notes: true
          draft: false
          prerelease: false
          make_latest: true

      - name: Checkout project
        uses: actions/checkout@v4

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src

      - name: "Collect sources"
        run: git archive --format=zip --output=sources.zip ${{ github.ref }}

      - name: "web-ext sign AMO"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          sourceCode: sources.zip
          channel: unlisted
          metaDataFile: amo-metadata.json
          approvalNotes: "Please find more information at https://github.com/Its-Alex/firefox-extension-searxng/"
          releaseNotes: ${{ github.event.release.body }}
          license: MIT
          apiKey: ${{ secrets.WEB_EXT_API_KEY }}
          apiSecret: ${{ secrets.WEB_EXT_API_SECRET }}
          timeout: 900000

      - name: "Attach release assets to release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          gh release upload $TAG_NAME \
            ${{ steps.web-ext-sign.outputs.target }}